# Generated by Django 4.1.5 on 2023-01-29 19:01

import MultiLang.custom_models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_article_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='test_lang',
            field=MultiLang.custom_models.MultiLanguageJSONField(default={}),
            preserve_default=False,
        ),
    ]
