# Generated by Django 4.1.5 on 2023-01-30 12:31

import MultiLang.custom_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_article_test_lang'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', MultiLang.custom_models.MultiLanguageJSONField()),
            ],
        ),
    ]
